config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :avengers
  # get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'avengers#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avenger.rb
class Avenger < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :avengers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avengers_controller.rb
class AvengersController < ApplicationController
  before_action :set_avenger, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /avengers or /avengers.json
  def index
    @avengers = Avenger.all
  end

  # GET /avengers/1 or /avengers/1.json
  def show
  end

  # GET /avengers/new
  def new
    # @avenger = Avenger.new
    @avenger = current_user.avengers.build
  end
  # GET /avengers/1/edit
  def edit
  end

  # POST /avengers or /avengers.json
  def create
   # @avenger = Avenger.new(avenger_params)
    @avenger = current_user.avengers.build(avenger_params)
    respond_to do |format|
      if @avenger.save
        format.html { redirect_to @avenger, notice: "Avenger was successfully created." }
        format.json { render :show, status: :created, location: @avenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @avenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avengers/1 or /avengers/1.json
  def update
    respond_to do |format|
      if @avenger.update(avenger_params)
        format.html { redirect_to @avenger, notice: "Avenger was successfully updated." }
        format.json { render :show, status: :ok, location: @avenger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @avenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avengers/1 or /avengers/1.json
  def destroy
    @avenger.destroy
    respond_to do |format|
      format.html { redirect_to avengers_url, notice: "Avenger was successfully destroyed." }
      format.json { head :no_content }
    end
  end

 # The correct user is the one to belong to this id current user
  def correct_user
    @avenger = current_user.avengers.find_by(id: params[:id])
    redirect_to avengers_path, notice:" Not Authorized" if @avenger.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avenger
      @avenger = Avenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def avenger_params
      params.require(:avenger).permit(:hero_name, :real_name, :age, :description, :statut, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @about_me = "This is a exemple of a instance variable"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avengers_helper.rb
module AvengersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/avengers/_form.html.erb
<%= form_with(model: avenger) do |form| %>
  <% if avenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avenger.errors.count, "error") %> prohibited this avenger from being saved:</h2>
      <ul>
        <% avenger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# label hero name is not display by removing the = sign%>
  <div class="field mb-3">
    <% form.label :hero_name %>
    <%= form.text_field :hero_name, class:"form-control",placeholder:"Hero name" %>
  </div>
  <div class="field mb-3">
    <%= form.text_field :real_name, class:"form-control", placeholder:"Real name"%>
  </div>
  <div class="field mb-3">
    <%= form.text_field :age, class:"form-control",placeholder:"Age" %>
  </div>
  <div class="field mb-3 ">
    <%= form.text_area :description, class:"form-control",placeholder:"Description", rows:"5" %>
  </div>
  <div class="field mb-3">
    <%= form.text_field :statut, class:"form-control",placeholder:"Statut" %>
  </div>
  <div class="field mb-3">
    <%= form.number_field :user_id, id: :avenger_user_id, class:"form-control",value:current_user.id, type: :hidden %>
  </div>
</br>
<div class="actions">
  <%= form.submit class:"btn btn-secondary" %>
</div>
<% end %>

app/views/avengers/edit.html.erb
<h1>Editing Avenger</h1>
<%= render 'form', avenger: @avenger %>
<%# Show button remove from view %>
<% link_to 'Show', @avenger %>
</br>
<%= link_to 'Delete', @avenger, method: :delete, class:"text-decoration-none btn btn-danger " , data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', avengers_path,class:"btn btn-dark" %>

app/views/avengers/index.html.erb
<% if user_signed_in? %>
  <h1 >Avengers list</h1>
  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Hero name</th>
        <th>Real name</th>
        <th>Statut</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @avengers.each do |avenger| %>
        <% if avenger.user == current_user%>
          <tr>
            <td><%= link_to avenger.hero_name, avenger ,class:"text-decoration-none" %></td>
            <td><%= avenger.real_name %></td>
            <td><%= avenger.statut %></td>
            <td><%= link_to 'Delete', avenger, method: :delete, class:"text-decoration-none btn btn-outline-danger btn-sm  " , data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Avenger', new_avenger_path,class:"btn btn-secondary" %>
<% else %>
  <div class="homepage">
  </div>
<% end %>

app/views/avengers/new.html.erb
<h1>Add New Avenger</h1>
</br>
<%= render 'form', avenger: @avenger %>
</br>
<%= link_to 'Back', avengers_path,class:"btn btn-dark" %>

app/views/avengers/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <h1 class="display-4 fw-bold"><%= @avenger.hero_name %></h1>
  <h3 class="display-10"><%= @avenger.real_name %></h3>
  <p>
    <strong>Age:</strong>
    <%= @avenger.age %>
  </p>
  <p class="lead"><%= @avenger.description %></p>
  <p>
    <strong>Statut:</strong>
    <%= @avenger.statut %>
  </p>
  <hr class="my-4">
  <%= link_to 'Edit', edit_avenger_path(@avenger),class:"btn btn-secondary" %>
  <%= link_to 'Back', avengers_path,class:"btn btn-dark" %></div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-2">
  <div class="container-fluid p-0">
    <%= link_to 'Marvel',root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About us',home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <% link_to 'Avengers',avengers_path, class:"nav-link" %>
        </li>
        <%# user navigation section %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Avenger',new_avenger_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out',destroy_user_session_path,method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile',edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up',new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In',new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
<%# <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> %>

app/views/home/about.html.erb
<div class="aboutPage">
  <p class=" aboutText">Home Project done in Ruby on Rails</p>
  <p><%= @about_me %></p>
</div>

app/views/home/index.html.erb
<div class="homepage ">
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Marvel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%# <div class="container p-0"> %>
    <%= render 'home/header' %></div>
</br>
<% if notice %>
  <%= render 'layouts/alerts' %>
<% end %>
<div class="container p-0">
  <%= yield %>
</div>
<!-- Optional JavaScript; choose one of the two! -->
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>
</html>